# Generated by Django 5.2.3 on 2025-06-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Уникальный email адрес клиента",
                        max_length=254,
                        unique=True,
                        verbose_name="Email адрес",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Полное имя"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о клиенте",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Пользователь, который создал этого клиента",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов"),
                    ("disable_client", "Может отключать клиентов"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Описательное название для удобства",
                        max_length=200,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "first_send_datetime",
                    models.DateTimeField(verbose_name="Дата и время первой отправки"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        help_text="Клиенты, которым будет отправлена рассылка",
                        to="mailings.client",
                        verbose_name="Получатели",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("disable_mailing", "Может отключать рассылки"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Подробная информация об ошибке или подтверждении",
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(verbose_name="Тело письма")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "permissions": [
                    ("view_all_messages", "Может просматривать все сообщения"),
                    ("disable_message", "Может отключать сообщения"),
                ],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailings.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
